export const GET_PROJECTS_LOADING = "GET_PROJECTS_LOADING"
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS"
export const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR"

export const GET_PROJECT_DETAILS_LOADING = "GET_PROJECT_DETAILS_LOADING"
export const GET_PROJECT_DETAILS_SUCCESS = "GET_PROJECT_DETAILS_SUCCESS"
export const GET_PROJECT_DETAILS_ERROR = "GET_PROJECT_DETAILS_ERROR"


export const GET_ONE_PROJECT_LOADING = "GET_ONE_PROJECT_LOADING"
export const GET_ONE_PROJECT_SUCCESS = "GET_ONE_PROJECT_SUCCESS"
export const GET_ONE_PROJECT_ERROR = "GET_ONE_PROJECT_ERROR"

export const ADD_PROJECT_DETAILS_LOADING = "ADD_PROJECT_DETAILS_LOADING"
export const ADD_PROJECT_DETAILS_SUCCESS = "ADD_PROJECT_DETAILS_SUCCESS"
export const ADD_PROJECT_DETAILS_ERROR = "ADD_PROJECT_DETAILS_ERROR"

export const UPDATE_PROJECT_DETAILS_LOADING = "UPDATE_PROJECT_DETAILS_LOADING"
export const UPDATE_PROJECT_DETAILS_SUCCESS = "UPDATE_PROJECT_DETAILS_SUCCESS"
export const UPDATE_PROJECT_DETAILS_ERROR = "UPDATE_PROJECT_DETAILS_ERROR"

export const DELETE_PROJECT_DETAILS_LOADING = "DELETE_PROJECT_DETAILS_LOADING"
export const DELETE_PROJECT_DETAILS_SUCCESS = "DELETE_PROJECT_DETAILS_SUCCESS"
export const DELETE_PROJECT_DETAILS_ERROR = "DELETE_PROJECT_DETAILS_ERROR"


export const ADD_TASK_LOADING = "ADD_TASK_LOADING"
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"
export const ADD_TASK_ERROR = "ADD_TASK_ERROR"


export const REMOVE_TASK_LOADING = "REMOVE_TASK_LOADING"
export const REMOVE_TASK_SUCCESS = "REMOVE_TASK_SUCCESS"
export const REMOVE_TASK_ERROR = "REMOVE_TASK_ERROR"

export const ADD_SUB_TASK_LOADING = "ADD_SUB_TASK_LOADING"
export const ADD_SUB_TASK_SUCCESS = "ADD_SUB_TASK_SUCCESS"
export const ADD_SUB_TASK_ERROR = "ADD_SUB_TASK_ERROR"


export const COMPLETE_SUB_TASK_LOADING = "COMPLETE_SUB_TASK_LOADING"
export const COMPLETE_SUB_TASK_SUCCESS = "COMPLETE_SUB_TASK_SUCCESS"
export const COMPLETE_SUB_TASK_ERROR = "COMPLETE_SUB_TASK_ERROR"