export const ADD_NEW_USER_LOADING = "ADD_NEW_USER_LOADING"
export const ADD_NEW_USER_SUCCESS = "ADD_NEW_USER_SUCCESS"
export const ADD_NEW_USER_ERROR = "ADD_NEW_USER_ERROR"

export const LOAD_USERS_LOADING = "LOAD_USERS_LOADING"
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS"
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR"

export const ASSIGN_PROJECT_LOADING = "ASSIGN_PROJECT_LOADING"
export const ASSIGN_PROJECT_SUCCESS = "ASSIGN_PROJECT_SUCCESS"
export const ASSIGN_PROJECT_ERROR = "ASSIGN_PROJECT_ERROR"


export const GET_USER_LOADING = "GET_USER_LOADING"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"